// i18n 语料同步脚本：读取 i18n/{common,app}/{locale}.json，生成各子工程原生格式
// 用法：node i18n/scripts/sync-i18n.mjs
//
// 修复说明（Code Review 004-i18n）：
//  - Web：只生成 locale 语料文件，不覆盖手写的 index.ts（index.ts 含 setLanguage/getLanguage）。
//  - Harmony：zh-CN 写入 base/（默认语言），en-US/zh-TW 写限定目录，保证 $r() 可解析。
//  - Android：沿用手工资源名（与语料点号键不同），故不在此自动生成，避免覆盖 values/strings.xml。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const LOCALES = ['zh-CN', 'en-US', 'zh-TW'];
const DOMAINS = ['common', 'app'];

// HarmonyOS 资源目录映射
const HARMONY_LOCALE_DIR = { 'zh-CN': 'base', 'en-US': 'en_US', 'zh-TW': 'zh_TW' };

function loadCorpus() {
  const corpus = {};
  for (const locale of LOCALES) {
    corpus[locale] = {};
    for (const domain of DOMAINS) {
      const file = resolve(ROOT, `i18n/${domain}/${locale}.json`);
      Object.assign(corpus[locale], JSON.parse(readFileSync(file, 'utf8')));
    }
  }
  return corpus;
}

// 点号 key → 资源名（Android/HarmonyOS 资源名不允许点号，转下划线）
function toResourceName(key) {
  return key.replace(/\./g, '_');
}

function writeWebVue(corpus) {
  const dir = resolve(ROOT, 'tpl-app-web/src/lang');
  mkdirSync(dir, { recursive: true });
  for (const locale of LOCALES) {
    const body = `// Auto-generated by i18n/scripts/sync-i18n.mjs — 请勿手动编辑\nconst messages = ${JSON.stringify(corpus[locale], null, 2)}\n\nexport default messages\n`;
    writeFileSync(resolve(dir, `${locale}.ts`), body, 'utf8');
  }
  // 注意：不生成 index.ts —— index.ts 手写维护（含 setLanguage/getLanguage/SUPPORTED_LOCALES）。
  console.log('[web]', dir, '(仅 locale 文件，未覆盖 index.ts)');
}

function writeHarmony(corpus) {
  const resDir = resolve(ROOT, 'tpl-app-harmony/products/default/src/main/resources');
  for (const locale of LOCALES) {
    const dir = resolve(resDir, HARMONY_LOCALE_DIR[locale], 'element');
    mkdirSync(dir, { recursive: true });
    const newStrings = Object.entries(corpus[locale]).map(([key, value]) => ({ name: toResourceName(key), value }));

    let strings = newStrings;
    if (locale === 'zh-CN') {
      // base/ 与既有资源（app_name/ability_label 等）合并，避免覆盖丢失
      const baseFile = resolve(dir, 'string.json');
      try {
        const existing = JSON.parse(readFileSync(baseFile, 'utf8'));
        const names = new Set(existing.string.map((s) => s.name));
        const merged = existing.string.slice();
        for (const s of newStrings) {
          if (!names.has(s.name)) merged.push(s);
        }
        strings = merged;
      } catch {
        // base/string.json 不存在则直接用语料
      }
    }
    writeFileSync(resolve(dir, 'string.json'), JSON.stringify({ string: strings }, null, 2) + '\n', 'utf8');
  }
  console.log('[harmony]', resDir, '(zh-CN→base, en-US→en_US, zh-TW→zh_TW)');
}

function writeMini(corpus) {
  const dir = resolve(ROOT, 'tpl-app-mini/miniprogram/i18n');
  mkdirSync(dir, { recursive: true });
  for (const locale of LOCALES) {
    const body = `// Auto-generated by i18n/scripts/sync-i18n.mjs — 请勿手动编辑\nexport default ${JSON.stringify(corpus[locale], null, 2)}\n`;
    writeFileSync(resolve(dir, `${locale}.ts`), body, 'utf8');
  }
  console.log('[mini]', dir);
}

const corpus = loadCorpus();
writeWebVue(corpus);
writeHarmony(corpus);
writeMini(corpus);
console.log('done');
