-- ----------------------------
-- tpl-app-api 初始化脚本
-- 创建 tpl-workspace 用户侧核心业务表
-- PostgreSQL 语法
-- ----------------------------

-- 1. 用户扩展信息表
CREATE TABLE IF NOT EXISTS tpl_user_profile (
    profile_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE,
    birth_date      DATE,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tpl_user_profile_user_id ON tpl_user_profile (user_id);

COMMENT ON TABLE tpl_user_profile IS '用户扩展信息表';
COMMENT ON COLUMN tpl_user_profile.profile_id IS '主键';
COMMENT ON COLUMN tpl_user_profile.user_id IS '关联 sys_user.user_id';
COMMENT ON COLUMN tpl_user_profile.birth_date IS '出生日期（选填）';
COMMENT ON COLUMN tpl_user_profile.create_time IS '创建时间';
COMMENT ON COLUMN tpl_user_profile.update_time IS '更新时间';

-- 2. 用户视图（糅合 sys_user + tpl_user_profile）
CREATE OR REPLACE VIEW tpl_user_view AS
SELECT
    u.user_id,
    u.user_name,
    u.nick_name,
    u.phone_number,
    u.email,
    u.avatar,
    u.status,
    u.del_flag,
    u.login_ip,
    u.login_date,
    u.create_time,
    p.birth_date
FROM sys_user u
LEFT JOIN tpl_user_profile p ON u.user_id = p.user_id
WHERE u.del_flag = '0';

COMMENT ON VIEW tpl_user_view IS '用户完整信息视图（sys_user + tpl_user_profile）';
